version: '3'
services:
  composer:
    image: composer:latest
    volumes:
      - ./src/laravel:/home/app/laravel
    working_dir: /home/app/laravel
    command: ["composer", "install"]
  nginx:
    build: docker/nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
  node:
    image: node:latest
    ports:
      - '3001:3001'
    volumes:
      - ./src/node:/home/app/node
    working_dir: /home/app/node
    command: bash -c "npm install && node index.js"
  nuxt:
    image: node:latest
    volumes:
      - ./src/nuxt:/home/app/nuxt
    working_dir: /home/app/nuxt
    command: [bash, -c, npm install && npm run dev]
  app:
    build: docker/php-fpm
    depends_on:
      - mysql
    environment:
      DB_HOST: 'mysql'
      DB_NAME: 'pascal'
      DB_USER: 'pascal'
      DB_PASS: 'uKXSjP3B4PDm'
    volumes:
      - ./src/laravel/:/var/www/html/laravel
    working_dir: /var/www/html/laravel
    command: [bash, -c, /opt/entrypoint.sh mysql pascal uKXSjP3B4PDm php artisan migrate && php-fpm]
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pascal
      MYSQL_USER: pascal
      MYSQL_PASSWORD: uKXSjP3B4PDm
    ports:
      - "13306:3306"
    volumes:
      - datavol:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "16379:6379"
volumes:
  datavol:
