FROM nginx:1.15.8

COPY etc/nginx/* /etc/nginx/conf.d/
#ADD entrypoint.sh /opt/entrypoint.sh

#RUN chmod a+x /opt/entrypoint.sh
#RUN /bin/bash -c "source /opt/entrypoint.sh /etc/letsencrypt/live/ssl_keys localhost"
