FROM php:7.1-fpm

ADD php.ini /usr/local/etc/php/conf.d/php.ini
ADD entrypoint.sh /opt/entrypoint.sh
RUN chmod a+x /opt/entrypoint.sh

RUN apt-get update \
  && docker-php-ext-install pdo_mysql mysqli mbstring
RUN apt-get install -y mysql-client

ENV PHPREDIS_VERSION php7

#RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz

#RUN tar xfz /tmp/redis.tar.gz \
#    && rm -r /tmp/redis.tar.gz \
#    && mkdir -p /usr/src/php/ext \
#    && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis \
#    && docker-php-ext-install redis
